# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UtilitySegmentMeasure
                                 A QGIS plugin
 Live Segment Tracker for Utility and Roadwork Takeoff
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-14
        copyright            : (C) 2026 by North of 29 LLC
        email                : ereams@northof29.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UtilitySegmentMeasure class from file UtilitySegmentMeasure.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .segmentmeasure import UtilitySegmentMeasure
    return UtilitySegmentMeasure(iface)
